# Generated by Django 5.0.1 on 2024-03-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0022_retinvoicereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='retaineritems',
            name='hsn',
            field=models.IntegerField(null=True),
        ),
    ]
