# Generated by Django 5.0.1 on 2024-04-11 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0026_retainer_payment_details'),
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetainerInvoiceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('retainer_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.retainerinvoice')),
            ],
        ),
    ]
