# Generated by Django 5.0.1 on 2024-04-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0028_retainerinvoicehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retainerinvoicehistory',
            name='company',
        ),
        migrations.RemoveField(
            model_name='retainerinvoicehistory',
            name='login_details',
        ),
        migrations.AlterField(
            model_name='retainerinvoicehistory',
            name='action',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='retainerinvoicehistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
