# Generated by Django 5.0.1 on 2024-04-18 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0031_rename_retainer_invoice_retainerinvoicehistory_retainer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retainerinvoicehistory',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='retainerinvoicehistory',
            name='user',
        ),
        migrations.AddField(
            model_name='retainerinvoicehistory',
            name='by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retainerinvoicehistory',
            name='action',
            field=models.CharField(max_length=100),
        ),
    ]
