# Generated by Django 5.0.1 on 2024-04-18 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0032_alter_retainerinvoicehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetainerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('by', models.CharField(max_length=100)),
                ('retainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.retainerinvoice')),
            ],
        ),
        migrations.DeleteModel(
            name='RetainerInvoiceHistory',
        ),
    ]
