# Generated by Django 5.0.1 on 2024-04-18 09:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0035_retainerinvoicehistory_delete_retainerhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retainerinvoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='retainerinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retainer_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retainerinvoice',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='retainerinvoice',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retainer_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RetainerInvoiceHistory',
        ),
    ]
