# Generated by Django 5.0.1 on 2024-04-19 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0036_retainerinvoice_created_at_and_more'),
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retainerinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retainer_created', to='Register_Login.logindetails'),
        ),
        migrations.AlterField(
            model_name='retainerinvoice',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retainer_modified', to='Register_Login.logindetails'),
        ),
    ]
