# Generated by Django 5.0.1 on 2024-04-20 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0037_alter_retainerinvoice_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retinvoicereference',
            name='company',
        ),
        migrations.RemoveField(
            model_name='retinvoicereference',
            name='logindetails',
        ),
        migrations.AlterField(
            model_name='retinvoicereference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
