# Generated by Django 5.0.1 on 2024-05-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0041_retainerinvoice_staff_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retainerinvoice',
            name='staff_member',
        ),
        migrations.AddField(
            model_name='retainerinvoice',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
