# Generated by Django 5.0.1 on 2024-05-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0043_retainerinvoice_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='retainerinvoice',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
