# Generated by Django 5.0.1 on 2024-05-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0044_retainerinvoice_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retainerinvoice',
            name='adjustment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='retainerinvoice',
            name='paid',
            field=models.IntegerField(null=True),
        ),
    ]
