# Generated by Django 5.0.1 on 2024-05-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0045_alter_retainerinvoice_adjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retainerinvoice',
            name='adjustment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retainerinvoice',
            name='paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
