# Generated by Django 5.0.1 on 2024-05-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0046_alter_retainerinvoice_adjustment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retainerinvoice',
            name='customer_name1',
        ),
    ]
